### ISSUE TITLE
Crashes using recent Node.js versions

### ISSUE THREAD

**Issue by jaydenseric** [jgillich/npm-check-engines#1]
This is such a great tool, but unfortunately it crashes using the recent Node.js versions:

<img width="940" alt="Screen Shot 2021-08-02 at 2 04 06 pm" src="https://user-images.githubusercontent.com/1754873/127802994-78dd3dac-bfd8-4a09-8d4d-d0002e36b291.png">

Also, there are deprecated dependency warnings. It would be awesome if this package could go a quick maintenance update; update or replace dependencies, ideally remove `lodash`, and get it going for currently supported Node.js versions.

The past few years I've been temporarily downgrading Node.js via nvm/asdf just to run this tool.

It would be cool if this tool were reliable enough to run it in package test scripts and CI.

**Comment by jgillich** [comment]
I have to say, I did not expect anyone to still be using this! Fix has been published, thanks for the notice
